// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4LjxOE_zWFw5xDvNsDZkwwaKw_pxxjpE',
    appId: '1:149879147563:web:9a90dd46907f155c196e6e',
    messagingSenderId: '149879147563',
    projectId: 'muse-me-123',
    authDomain: 'muse-me-123.firebaseapp.com',
    storageBucket: 'muse-me-123.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBa5hpPuYl8Z_JmOPk0pORnAzBzi6caD4E',
    appId: '1:149879147563:android:0cab422faac5b3fa196e6e',
    messagingSenderId: '149879147563',
    projectId: 'muse-me-123',
    storageBucket: 'muse-me-123.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlgOd7nUJTAt_pzZscz3MQaQ5wmtqMpvw',
    appId: '1:149879147563:ios:92b0e3fec5b2e3ec196e6e',
    messagingSenderId: '149879147563',
    projectId: 'muse-me-123',
    storageBucket: 'muse-me-123.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlgOd7nUJTAt_pzZscz3MQaQ5wmtqMpvw',
    appId: '1:149879147563:ios:92b0e3fec5b2e3ec196e6e',
    messagingSenderId: '149879147563',
    projectId: 'muse-me-123',
    storageBucket: 'muse-me-123.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4LjxOE_zWFw5xDvNsDZkwwaKw_pxxjpE',
    appId: '1:149879147563:web:b82d4317c6ca1cc8196e6e',
    messagingSenderId: '149879147563',
    projectId: 'muse-me-123',
    authDomain: 'muse-me-123.firebaseapp.com',
    storageBucket: 'muse-me-123.appspot.com',
  );
}
